# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

neogradle.subsystems.parchment.minecraftVersion=1.21
neogradle.subsystems.parchment.mappingsVersion=2024.06.23

mapping_channel=official
mapping_version=1.21.1

# Mod
mod_authors=RazorDevs
mod_license=LGPL-3.0
mod_id=ascended_quark
mod_name=Ascended Quark
mod_version=1.1.6-beta
mc_version=1.21.1
neoforge_version=21.1.192
neoforge_version_range=[21.1.0,)

mod_description = A small mod that aims to bring compatibility between Quark and the Aether mod! (And Addons too!)

# Dependencies
aether_version=1.21.1-1.5.10-neoforge
nitrogen_version=1.21.1-1.1.25-neoforge
cumulus_version=1.21.1-2.0.8-neoforge
accessories_version=1.1.0-beta.16
cloth_config_version=15.0.140
quark_version=7980026
zeta_version=7980010
jei_version=19.27.0.340

terrablender_version=1.21.1-4.1.0.8
deep_aether_version=7843283
