modLoader="javafml"
loaderVersion="[47,)"
license = "Assets: All Rights Reserved; Code: GPL-3.0"
issueTrackerURL="https://github.com/RazorDevs/Ascended-Quark/issues"

[[mods]]
modId="ascended_quark"
version="${file.jarVersion}"
displayName="Ascended Quark"
authors="RazorDevs"
description='''
mod_description = A small mod that aims to bring compatibility between quark and the aether mod!
'''
logoFile="ascended_quark.png"
credits="A special thanks goes to the creators behind Quark and the Aether mods!"

[[dependencies.ascended_quark]]
modId="forge"
mandatory=true
versionRange="[47.1.0,)"
ordering="NONE"
side="BOTH"
[[dependencies.ascended_quark]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"

[[dependencies.ascended_quark]]
modId="quark"
mandatory=true
versionRange="[0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.ascended_quark]]
modId="aether"
mandatory=true
versionRange="[1.2.0,)"
ordering="AFTER"
side="BOTH"