
modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
[[mods]]
modId="ascended_quark"
version="${file.jarVersion}"
displayName="Ascended Quark"

logoFile="ascended_quark.png"
credits="A special thanks goes to the creators behind Quark and Aether"
authors="RazorDevs"
description='''
A mod that adds compatability between Aether and Quark
'''

[[dependencies.ascended_quark]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ascended_quark]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ascended_quark]]
    modId="quark"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ascended_quark]]
    modId="aether"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"