modLoader="javafml"
loaderVersion="${forge_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/RazorDevs/Ascended-Quark/issues"

[[mods]]
modId="${mod_id}"
version="${file.jarVersion}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''
logoFile="${mod_id}.png"
credits="A special thanks goes to the creators behind Quark and the Aether mods!"

[[dependencies.ascended_quark]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.ascended_quark]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.ascended_quark]]
    modId="quark"
    mandatory=true
    versionRange="${quark_version}"
    ordering="AFTER"
    side="BOTH"

[[dependencies.ascended_quark]]
    modId="aether"
    mandatory=true
    versionRange="${aether_version}"
    ordering="AFTER"
    side="BOTH"